2020-01-09 20:44:53,391 ERROR: Exception on /explore [GET] [in /Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/lukazphelps/Desktop/SchoolCode/Mythril_Sheets/app/routes.py", line 157, in explore
    return render_template('sheets.html', title='Explore', sheets=sheets)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/lukazphelps/Desktop/SchoolCode/Mythril_Sheets/app/templates/sheets.html", line 9, in <module>
    {% for field in form if field.name != "csrf_token" % }
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 197, in parse_for
    test = self.parse_expression()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 480, in parse_compare
    ops.append(nodes.Operand(token_type, self.parse_math1()))
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 520, in parse_math2
    next(self.stream)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/lexer.py", line 681, in tokeniter
    raise TemplateSyntaxError('unexpected \'%s\'' %
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2020-01-09 20:46:09,470 ERROR: Exception on /explore [GET] [in /Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/lukazphelps/Desktop/SchoolCode/Mythril_Sheets/app/routes.py", line 157, in explore
    return render_template('sheets.html', title='Explore', sheets=sheets)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/lukazphelps/Desktop/SchoolCode/Mythril_Sheets/app/templates/sheets.html", line 14, in <module>
    {% endfor % }
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/lukazphelps/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'.
